insert into public.creators (slug, name, headline, bio, location, followers_count)
values
  (
    'mira-sol',
    'Mira Sol',
    'Memory-rich speculative dramas built for long night watches.',
    'Mira designs AI-native films that feel architectural, intimate, and emotionally precise. Her work leans into slower pacing and high-payoff visual motifs.',
    'Barcelona',
    18400
  ),
  (
    'jun-vale',
    'Jun Vale',
    'Slow-burn thrillers with digital weather and human fragility.',
    'Jun''s films are tightly controlled mysteries, often driven by artificial landscapes and obsessive character studies.',
    'Seoul',
    11200
  ),
  (
    'anik-dey',
    'Anik Dey',
    'Mythic science-fiction cinema with a devotional sense of scale.',
    'Anik uses AI workflows to build full-length speculative worlds, often fusing spiritual imagery with stark future architecture.',
    'Kolkata',
    9700
  ),
  (
    'ari-nox',
    'Ari Nox',
    'Nocturnal AI cinema with dense sound design and patient reveals.',
    'Ari works in darker emotional registers, using AI not for novelty but for atmosphere, tension, and ritualized framing.',
    'Los Angeles',
    7900
  )
on conflict (slug) do nothing;

insert into public.collections (slug, name, description)
values
  (
    'festival-contenders',
    'Festival Contenders',
    'Long-form AI films with strong directorial voice, polished pacing, and awards potential.'
  ),
  (
    'midnight-surrealism',
    'Midnight Surrealism',
    'A late-night shelf of slower, stranger films built for headphones and uninterrupted attention.'
  ),
  (
    'first-100',
    'First 100',
    'The earliest accepted titles in the public catalog, permanently identified by serial.'
  )
on conflict (slug) do nothing;

insert into public.films (
  serial_number,
  creator_id,
  slug,
  title,
  logline,
  synopsis,
  youtube_url,
  runtime_minutes,
  release_year,
  format,
  genre,
  mood,
  languages,
  tools,
  featured_weight,
  visibility,
  discussion_count,
  views_count,
  saves_count,
  published_at
)
values
  (
    1,
    (select id from public.creators where slug = 'mira-sol'),
    'afterlight-valley',
    'Afterlight Valley',
    'A grieving architect builds a final city from memory and discovers the simulation remembers her back.',
    'Set inside a half-finished memorial metropolis, Afterlight Valley follows an architect who uses AI-generated reconstruction tools to preserve the voice of her late sister. As the city gains detail, the remembered world begins editing itself, forcing her to confront what is truly memory and what is now invention.',
    'https://www.youtube.com/watch?v=yplb0yBEiRo',
    82,
    2026,
    'feature film',
    'Speculative drama',
    'haunting',
    array['English'],
    array['Sora', 'Runway', 'ElevenLabs'],
    100,
    'public',
    214,
    142000,
    18200,
    '2026-02-28T00:00:00Z'
  ),
  (
    7,
    (select id from public.creators where slug = 'jun-vale'),
    'glass-horizon',
    'Glass Horizon',
    'A weather forecaster starts receiving tomorrow''s storm warnings from a city that no longer exists.',
    'Glass Horizon turns climate data into supernatural suspense. A quiet forecaster begins decoding impossible visual glitches in a coastal warning network and follows the trail into the abandoned AI training city that produced them.',
    'https://www.youtube.com/watch?v=pD4q9zwWvRg',
    64,
    2026,
    'mid-length film',
    'Mystery',
    'ominous',
    array['Korean', 'English'],
    array['Veo', 'Runway', 'ElevenLabs'],
    86,
    'public',
    132,
    88000,
    9600,
    '2026-02-18T00:00:00Z'
  ),
  (
    12,
    (select id from public.creators where slug = 'anik-dey'),
    'echoes-for-avalon',
    'Echoes for Avalon',
    'An exiled astronomer journeys across a machine-grown kingdom to recover a stolen star-map that can restart the seasons.',
    'Echoes for Avalon mixes myth, science fiction, and ceremonial pacing. It follows an astronomer exiled from a kingdom whose sky is generated by a failing machine, and whose only repair manual survives as a sacred text.',
    'https://www.youtube.com/watch?v=T37_nxS_qQw',
    97,
    2026,
    'feature film',
    'Fantasy',
    'mythic',
    array['English', 'Bengali'],
    array['Kling', 'Sora', 'Luma'],
    94,
    'public',
    178,
    119000,
    14900,
    '2026-03-01T00:00:00Z'
  ),
  (
    18,
    (select id from public.creators where slug = 'ari-nox'),
    'static-bloom',
    'Static Bloom',
    'A botanist trapped in a dead signal zone discovers flowers that replay human voices when exposed to moonlight.',
    'Static Bloom is a patient, moonlit mystery where the natural world becomes a storage medium. The film uses sparse dialogue and long image sequences to build its emotional effect.',
    'https://www.youtube.com/watch?v=ON_8eCuVtnA',
    54,
    2026,
    'mid-length film',
    'Sci-fi',
    'dreamlike',
    array['English'],
    array['Runway', 'Pika', 'Suno'],
    78,
    'public',
    94,
    61000,
    8100,
    '2026-01-24T00:00:00Z'
  ),
  (
    24,
    (select id from public.creators where slug = 'mira-sol'),
    'orchard-of-zero',
    'Orchard of Zero',
    'A mother travels through synthetic orchards to rebuild the final message her son left inside an abandoned training model.',
    'Orchard of Zero is a quieter, more intimate film about grief and reconstruction. Its visual language uses slowly mutating agricultural spaces to represent neural memory decay.',
    'https://www.youtube.com/watch?v=pbBZCGBD01M',
    71,
    2025,
    'feature film',
    'Drama',
    'meditative',
    array['Spanish', 'English'],
    array['Sora', 'Luma', 'ElevenLabs'],
    82,
    'public',
    121,
    93000,
    11400,
    '2025-12-12T00:00:00Z'
  ),
  (
    31,
    (select id from public.creators where slug = 'anik-dey'),
    'salt-atlas',
    'Salt Atlas',
    'Two mapmakers cross an evaporated sea to chart the last surviving weather towers before the monsoon returns.',
    'Salt Atlas is a more open, hopeful road film about siblings, climate memory, and impossible geography. It balances spectacle with a warm human core.',
    'https://www.youtube.com/watch?v=mEVl0NS0vu8',
    46,
    2025,
    'mid-length film',
    'Adventure',
    'uplifting',
    array['English'],
    array['Veo', 'Kling', 'Suno'],
    69,
    'public',
    88,
    57000,
    6400,
    '2025-11-02T00:00:00Z'
  ),
  (
    42,
    (select id from public.creators where slug = 'jun-vale'),
    'the-quiet-machine',
    'The Quiet Machine',
    'A compliance officer investigating a vanished research lab finds a machine that only speaks when no one is recording.',
    'The Quiet Machine is built around procedural tension, dialogue minimalism, and increasingly hostile architecture. It is one of the strongest examples of long-form AI suspense in the catalog.',
    'https://www.youtube.com/watch?v=KKm5foh8mOw',
    88,
    2025,
    'feature film',
    'Thriller',
    'ominous',
    array['English', 'Korean'],
    array['Sora', 'Runway', 'ElevenLabs'],
    98,
    'public',
    243,
    166000,
    19100,
    '2025-10-18T00:00:00Z'
  )
on conflict (serial_number) do nothing;

select setval('public.film_serial_seq', greatest((select coalesce(max(serial_number), 0) from public.films), 1), true);

insert into public.collection_films (collection_id, film_id, position)
values
  (
    (select id from public.collections where slug = 'festival-contenders'),
    (select id from public.films where serial_number = 1),
    1
  ),
  (
    (select id from public.collections where slug = 'festival-contenders'),
    (select id from public.films where serial_number = 7),
    2
  ),
  (
    (select id from public.collections where slug = 'festival-contenders'),
    (select id from public.films where serial_number = 12),
    3
  ),
  (
    (select id from public.collections where slug = 'festival-contenders'),
    (select id from public.films where serial_number = 24),
    4
  ),
  (
    (select id from public.collections where slug = 'festival-contenders'),
    (select id from public.films where serial_number = 42),
    5
  ),
  (
    (select id from public.collections where slug = 'midnight-surrealism'),
    (select id from public.films where serial_number = 7),
    1
  ),
  (
    (select id from public.collections where slug = 'midnight-surrealism'),
    (select id from public.films where serial_number = 18),
    2
  ),
  (
    (select id from public.collections where slug = 'midnight-surrealism'),
    (select id from public.films where serial_number = 42),
    3
  ),
  (
    (select id from public.collections where slug = 'first-100'),
    (select id from public.films where serial_number = 1),
    1
  ),
  (
    (select id from public.collections where slug = 'first-100'),
    (select id from public.films where serial_number = 12),
    2
  ),
  (
    (select id from public.collections where slug = 'first-100'),
    (select id from public.films where serial_number = 18),
    3
  ),
  (
    (select id from public.collections where slug = 'first-100'),
    (select id from public.films where serial_number = 31),
    4
  ),
  (
    (select id from public.collections where slug = 'first-100'),
    (select id from public.films where serial_number = 42),
    5
  )
on conflict (collection_id, film_id) do nothing;
